name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*'
      - 'mkdocs.yml'
      - 'requirements.docs.txt'
      - '.github/workflows/docs-publish.yaml'
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manually Build Docs'
        default: 'Just want to build it'
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Install
        run: poetry install
      - name: Deploy mkdocs
        run: poetry run mkdocs gh-deploy --force
